apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: demo-service
#  namespace: monitoring
  labels:
    release: observa
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: demo-service
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
